### ISSUE TITLE
Authentication session is active even after user is deleted from Firebase

### ISSUE THREAD

**Issue by sibijosephv** [react-native-market/firebase-authentication-kit#17]
I have phone auth enabled. I deleted the user account from firebase, and refreshed the app on the simulator. The user session was still active even after the user itself was deleted from Firebase. Why is it so?

**Comment by sibijosephv** [comment]
Any update?

**Comment by Salakar** [comment]
I think this is just the way the Firebase SDKs behave on device and I'm not sure there is anything you could do about it to be honest, it will after a couple of mins/hours no longer be active, if you need it instantly I think your best bet is deleting the user on the device rather than the via console, via this method: https://invertase.io/oss/react-native-firebase/v6/auth/reference/user#delete

Sources re persistence: https://stackoverflow.com/questions/27893418/firebase-deleting-and-reinstalling-app-does-not-un-authenticate-a-user
